import Head from "next/head";
import Projects from "~/components/Projects";
import Socials from "~/components/Socials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stilian Balasopoulov</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col md:flex-row gap-2">
        <div className="bg-gray-300 p-2 flex-grow"></div>
        <div className="bg-gray-300 p-2 flex-grow flex flex-col gap-2 ">
          <Projects />
          <Socials />
        </div>
      </main>
    </>
  );
}
