import Head from "next/head";
import Landing from "~/components/Landing";
import Projects from "~/components/Projects";
import Socials from "~/components/Socials";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stilian Balasopoulov</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col md:flex-row gap-2 p-2 mocha text-text bg-base">
        <div className="bg-crust p-2 flex-grow rounded-md">
          <Landing />
        </div>
        <div className="bg-crust p-2 flex-grow flex flex-col gap-2 rounded-md">
          <Projects />
          <Socials />
        </div>
      </main>
    </>
  );
}
