import Head from "next/head";
import Script from "next/script";
import Landing from "~/components/landing/Landing";
import Projects from "~/components/info/projects/Projects";
import Socials from "~/components/info/socials/Socials";
import Info from "~/components/info/Info";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stilian Balasopoulov</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/5dffb3fca8.js"
        crossorigin="anonymous"
      />
      <main className="mocha flex min-h-screen flex-col gap-2 bg-base p-2 text-text md:flex-row">
        <Landing />
        <Info />
      </main>
    </>
  );
}
